# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/aljeter/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/motorola/aljeter/proprietary/etc/firmware/emmc_ffu_15_RC14MB.fw:system/etc/firmware/emmc_ffu_15_RC14MB.fw \
    vendor/motorola/aljeter/proprietary/etc/firmware/emmc_ffu_15_RC1BMB.fw:system/etc/firmware/emmc_ffu_15_RC1BMB.fw \
    vendor/motorola/aljeter/proprietary/etc/firmware/emmc_ffu_15_RE1BMB.fw:system/etc/firmware/emmc_ffu_15_RE1BMB.fw \
    vendor/motorola/aljeter/proprietary/etc/firmware/emmc_ffu_15_RX14MB.fw:system/etc/firmware/emmc_ffu_15_RX14MB.fw \
    vendor/motorola/aljeter/proprietary/etc/firmware/emmc_ffu_15_RX1BMB.fw:system/etc/firmware/emmc_ffu_15_RX1BMB.fw \
    vendor/motorola/aljeter/proprietary/etc/firmware/ice40.bin:system/etc/firmware/ice40.bin \
    vendor/motorola/aljeter/proprietary/etc/firmware/wlan/prima/WCNSS_cfg.dat:system/etc/firmware/wlan/prima/WCNSS_cfg.dat \
    vendor/motorola/aljeter/proprietary/framework/cneapiclient.jar:system/framework/cneapiclient.jar \
    vendor/motorola/aljeter/proprietary/framework/com.quicinc.cne.jar:system/framework/com.quicinc.cne.jar \
    vendor/motorola/aljeter/proprietary/framework/com.quicinc.cne.server-V1.0-java.jar:system/framework/com.quicinc.cne.server-V1.0-java.jar \
    vendor/motorola/aljeter/proprietary/framework/com.quicinc.cne.server-V2.0-java.jar:system/framework/com.quicinc.cne.server-V2.0-java.jar \
    vendor/motorola/aljeter/proprietary/framework/com.quicinc.cne.server-V2.1-java.jar:system/framework/com.quicinc.cne.server-V2.1-java.jar \
    vendor/motorola/aljeter/proprietary/framework/com.quicinc.cne.server-V2.2-java.jar:system/framework/com.quicinc.cne.server-V2.2-java.jar \
    vendor/motorola/aljeter/proprietary/framework/embmslibrary.jar:system/framework/embmslibrary.jar \
    vendor/motorola/aljeter/proprietary/framework/izat.xv.srv.jar:system/framework/izat.xv.srv.jar \
    vendor/motorola/aljeter/proprietary/framework/qti-telephony-common.jar:system/framework/qti-telephony-common.jar

PRODUCT_PACKAGES += \
    QtiTelephonyService \
    embms \
    CNEService \
    atfwd \
    ims \
    qcrilmsgtunnel \
    QPerformance \
    QtiTelephonyServicelibrary \
    UxPerformance \
    qcrilhook
